config/routes.rb
Rails.application.routes.draw do

  get 'homepage/index'
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create]

  # resources generate an id, in this case user's id
  	# to override users,controller for users is changed from "clearance/users" to "users"
  resources :users, controller: "users", only: [:create, :edit, :update, :show, :index] do
	# get "/users" => "users#index"
	# get "/users/:id" => "users#show"

  	# resource doesn't generate an id (password is just a column, not a table)
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  	# leads to views => welcome => index
	  root 'welcome#index'

  	# page with sign up form             #new is the method used
  	get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  	delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  	get "/sign_up" => "users#new", as: "sign_up"

	# user clicked on form -> google, users will get redirected back
	get "/auth/:provider/callback" => "sessions#create_from_omniauth"

	# homepage
	get "/homepage" => "homepage#index"
  
	# nested routes
	resources :listings do
    resources :reservations
  end
	# replaces:
	# get "/listing" => "listing#index"
	# post "/listing/index" => "listing#create"
	# get "/listing/:id" => "listing#show"
	# get "/listing/:id/edit" => "listing#show#edit"

	patch "/listings/:id/verify" => "listings#verify", as: "verify"

  post "/listings/match" => "listings#match", as: "match"
  post "/listings/search" => "listings#search", as: "search"

  get 'reservations/:id/braintree/new' => 'braintree#new', as: "new_braintree"
  post 'reservations/:id/braintree/checkout' => 'braintree#checkout', as: "checkout_braintree"
  #
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/listing.rb
class Listing < ApplicationRecord

	belongs_to :user

	has_many :reservations, dependent: :destroy

	validates :title, presence: true
	validates :room_type, presence: true
	validates :city, presence: true
	validates :pricing, presence: true

	mount_uploaders :images, ImageUploader


	scope :search_city, -> (x) { where("city ILIKE ?", "%#{x}%") }
	scope :search_title, -> (y) { where("title ILIKE ?", "%#{y}%") }

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  #             clearance method
  before_action :require_login, only: [:new, :create, :edit, :update, :verify, :destroy]
  before_action :find_listing, only: [:show, :edit, :verify, :update, :destroy]
  before_action :check_update_rights, only: [:update, :edit]
  before_action :check_verification_rights, only: [:verify]
  before_action :ajax_search, only: [:match, :search]

  def index
  end

  def new
    @listing = Listing.new
  end

  def show
    # @reservation = Reservation.new
  end

  def create
  	listing = Listing.new(listing_params)
    # specify the owner of the listing
  	listing.user_id = current_user.id
  	if listing.save
      flash[:listing_saved] = "Successfully created listing."
  	  redirect_to homepage_path
    else
      flash[:blank] = "#{listing.errors.full_messages}"
      redirect_back(fallback_location: homepage_path)
      # redirect_to :back 
    end
  end

  def edit
    # only user || admin can edit & update
  end

  def update
    @listing.update(edit_listing_params)
    flash[:updated_listing] = "Listing updated!"
    redirect_to listing_path(@listing)
  end

  def verify
    if @listing.verification? == true
      @listing.update(verification:false)
    else
      @listing.update(verification:true)
    end

    if @listing.save
      redirect_to listing_path(@listing)
    end
  end

  def match
    respond_to do |format|
      format.json { render json: @listings }
      format.html
    end
  end

  def search
    if params[:city_search].blank? && params[:title_search].blank?
      flash[:no_match] = "Sorry! No match found."
      redirect_back(fallback_location: homepage_path)
    elsif !@listings.empty?
      render :index #=> listings/index.erb
    else 
      flash[:no_match] = "Sorry! No match found."
      redirect_back(fallback_location: homepage_path)
    end
  end

  def destroy
    @listing.destroy
    respond_to do |format|
      format.js
    end
  end

  private
  def find_listing
    @listing = Listing.find(params[:id])
  end

  def listing_params
    # strong params
  	params.require(:listing).permit(:title, :city, :address, :summary, :description, :home_type, :room_type, :guest_number, :pricing, :user_id, {images: []}, :amenity => [])
  end

  def edit_listing_params
    params.require(:listing).permit(:title, :summary, :description, :home_type, :room_type, :guest_number, :pricing, {images: []}, :amenity => [])
  end

  def check_update_rights
    @listing = Listing.find(params[:id])
    if current_user.role != @listing.user_id && current_user.moderator? 
      redirect_to homepage_path
    end
  end

  def check_verification_rights
    if !current_user.superadmin? || !current_user.moderator?
      # flash[:error] = "Access denied"
      flash[:changed] = "verification edited"
    end
  end

  def ajax_search
    @listings = Listing.all
    #                                        search is from the form at applicaition.html.erb where name="search"
    @listings = @listings.search_city(params[:city_search]) if params[:city_search].present? #=> [].city listing_obj.city
    @listings = @listings.search_title(params[:title_search]) if params[:title_search].present?
  end

end

app/helpers/listing_helper.rb
module ListingHelper
end

app/views/listings/destroy.js.erb
// to test
console.log("this page was loaded")

$("#<%= @listing.id %>").fadeOut()

app/views/listings/edit.erb
<div class="container" style="margin-bottom: 7vh">

	<%= @listing.inspect %>

	<h3><%= @listing.title %></h3>

	<hr/>

	<h4>Available edit fields:</h4>

	<%= form_with scope: @listing, url: listing_path, method: "patch", local: true do |form| %>

		<div>
			<%= form.label :title %><br>
			<%= form.text_field :title %>
		</div>

		<div>
			<%= form.label :summary %><br>
			<%= form.text_area :summary %>
		</div>

		<div>
			<%= form.label :description %><br>
			<%= form.text_area :description %>
		</div>

		<div>
			<%= form.label :home_type %><br>
			<%= form.radio_button :home_type, "Apartment" %>
			Apartment
			<%= form.radio_button :home_type, "House" %>
			House
			<%= form.radio_button :home_type, "Bed and Breakfast" %>
			Bed & Breakfast
			<%= form.radio_button :home_type, "Other" %>
			Other
		</div>

		<div>
			<%= form.label :room_type %><br>
			<%= form.radio_button :room_type, "Entire place" %>
			Entire home/apt
			<%= form.radio_button :room_type, "Private room" %>
			Private room
			<%= form.radio_button :room_type, "Shared room" %>
			Shared room
		</div>

		<div>
			<%= form.label :amenities %><br>
			<%= form.check_box :amenity, {:multiple => true}, "Self check-in", nil %>
			Self check-in
			<%= form.check_box :amenity, {:multiple => true}, "Pool", nil %>
			Pool
			<%= form.check_box :amenity, {:multiple => true}, "Gym", nil %>
			Gym
			<%= form.check_box :amenity, {:multiple => true}, "Kitchen", nil %>
			Kitchen
			<%= form.check_box :amenity, {:multiple => true}, "Washer", nil %>
			Washer
			<%= form.check_box :amenity, {:multiple => true}, "Dryer", nil %>
			Dryer
			<%= form.check_box :amenity, {:multiple => true}, "Dishwasher", nil %>
			Dishwasher
			<%= form.check_box :amenity, {:multiple => true}, "Elevator", nil %>
			Elevator
			<%= form.check_box :amenity, {:multiple => true}, "Buzzer", nil %>
			Buzzer
			<%= form.check_box :amenity, {:multiple => true}, "Doorman", nil %>
			Doorman
			<%= form.check_box :amenity, {:multiple => true}, "Game console", nil %>
			Game console
			<%= form.check_box :amenity, {:multiple => true}, "Pets allowed", nil %>
			Pets allowed
			<%= form.check_box :amenity, {:multiple => true}, "Heating", nil %>
			Heating
			<%= form.check_box :amenity, {:multiple => true}, "Air conditioning", nil %>
			Air conditioning
			<%= form.check_box :amenity, {:multiple => true}, "Wifi", nil %>
			Wifi
			<%= form.check_box :amenity, {:multiple => true}, "TV", nil %>
			TV
			<%= form.check_box :amenity, {:multiple => true}, "Bathroom essentials", nil %>
			Bathroom essentials
			<%= form.check_box :amenity, {:multiple => true}, "Bedroom comforts", nil %>
			Bedroom comforts
			<%= form.check_box :amenity, {:multiple => true}, "Coffee maker", nil %>
			Coffee maker
			<%= form.check_box :amenity, {:multiple => true}, "Smoke detector", nil %>
			Smoke detector
			<%= form.check_box :amenity, {:multiple => true}, "Free parking on premises", nil %>
			Free parking on premises
		</div>

		<div>
			<%= form.label :accommodates %><br>
			<%= form.text_field :guest_number %>
		</div>

		<div>
			<%= form.label :pricing %><br>
			<%= form.text_field :pricing %>
		</div>

		<div>
			<%= form.label :images %><br>
			<%= form.file_field :images, multiple: true %>
		</div>

		<br/>

		<div>
			<%= form.submit %>
		</div>

	<% end %>
	
</div>

app/views/listings/index.erb
<div class="container" style="margin-bottom: 7vh">

	<div class="mt-2 mb-4">Search results for <%= @listings[0].title %></div>

	<div class="row">
		<% @listings.order("created_at DESC").each do |listing| %>
			<div class="col-4">
				<div class="card mb-4">
					<% if listing.images != [] %>
						<%= image_tag listing.images[0].thumb.url %><br />
					<% else %>
						<img class="card-img-top" src="https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?ixlib=rb-0.3.5&s=6286e40d53d85d1fe9fb0f2fae05c173&auto=format&fit=crop&w=1050&q=80" alt="Card image cap">
					<% end %>
					<div class="card-body">
						<a href="/listings/<%= listing.id %>" class="card-title"><%= listing.title %></h5></a>
						<p class="card-text"><%= listing.room_type %> • <%= listing.city %></p>
					</div>
				</div>
			</div>
		<% end %>
	</div>

</div>

app/views/listings/new.erb
<div class="container" style="margin-bottom: 7vh">

  <div class="d-flex flex-column bd-highlight mb-3">

    <h2 class="p-2 bd-highlight">Add listing</h2>

    <%= form_with scope: @listing, url: listings_path, local: true do |form| %>

      <div class="p-2 bd-highlight">
        <%= form.label :title %><br>
        <%= form.text_field :title %>
      </div>

      <div class="p-2 bd-highlight" style="margin-top: 1.5vh;">
        <%= form.label :city %><br>
        <%= form.text_field :city %>
      </div>

      <div class="p-2 bd-highlight" style="margin-top: 1.5vh;">
        <%= form.label :address %><br>
        <%= form.text_field :address %>
      </div>

      <div class="p-2 bd-highlight" style="margin-top: 1.5vh;">
        <%= form.label :summary %><br>
        <%= form.text_area :summary %>
      </div>

      <div class="p-2 bd-highlight" style="margin-top: 1.5vh;">
        <%= form.label :description %><br>
        <%= form.text_area :description %>
      </div>

      <div class="p-2 bd-highlight" style="margin-top: 1.5vh;">
        <%= form.label :home_type %><br>
        <%= form.radio_button :home_type, "Apartment" %>
        Apartment
        <%= form.radio_button :home_type, "House" %>
        House
        <%= form.radio_button :home_type, "Bed and Breakfast" %>
        Bed & Breakfast
        <%= form.radio_button :home_type, "Other" %>
        Other
      </div>

      <div class="p-2 bd-highlight" style="margin-top: 1.5vh;">
        <%= form.label :room_type %><br>
        <%= form.radio_button :room_type, "Entire place" %>
        Entire home/apt
        <%= form.radio_button :room_type, "Private room" %>
        Private room
        <%= form.radio_button :room_type, "Shared room" %>
        Shared room
      </div>

      <div class="p-2 bd-highlight" style="margin-top: 1.5vh;">
        <%= form.label :amenities %><br>
        <%= form.check_box :amenity, {:multiple => true}, "Self check-in", nil %>
        Self check-in
        <%= form.check_box :amenity, {:multiple => true}, "Pool", nil %>
        Pool
        <%= form.check_box :amenity, {:multiple => true}, "Gym", nil %>
        Gym
        <%= form.check_box :amenity, {:multiple => true}, "Kitchen", nil %>
        Kitchen
        <%= form.check_box :amenity, {:multiple => true}, "Washer", nil %>
        Washer
        <%= form.check_box :amenity, {:multiple => true}, "Dryer", nil %>
        Dryer
        <%= form.check_box :amenity, {:multiple => true}, "Dishwasher", nil %>
        Dishwasher
        <%= form.check_box :amenity, {:multiple => true}, "Elevator", nil %>
        Elevator
        <%= form.check_box :amenity, {:multiple => true}, "Buzzer", nil %>
        Buzzer
        <%= form.check_box :amenity, {:multiple => true}, "Doorman", nil %>
        Doorman
        <%= form.check_box :amenity, {:multiple => true}, "Game console", nil %>
        Game console
        <%= form.check_box :amenity, {:multiple => true}, "Pets allowed", nil %>
        Pets allowed
        <%= form.check_box :amenity, {:multiple => true}, "Heating", nil %>
        Heating
        <%= form.check_box :amenity, {:multiple => true}, "Air conditioning", nil %>
        Air conditioning
        <%= form.check_box :amenity, {:multiple => true}, "Wifi", nil %>
        Wifi
        <%= form.check_box :amenity, {:multiple => true}, "TV", nil %>
        TV
        <%= form.check_box :amenity, {:multiple => true}, "Bathroom essentials", nil %>
        Bathroom essentials
        <%= form.check_box :amenity, {:multiple => true}, "Bedroom comforts", nil %>
        Bedroom comforts
        <%= form.check_box :amenity, {:multiple => true}, "Coffee maker", nil %>
        Coffee maker
        <%= form.check_box :amenity, {:multiple => true}, "Smoke detector", nil %>
        Smoke detector
        <%= form.check_box :amenity, {:multiple => true}, "Free parking on premises", nil %>
        Free parking on premises
      </div>

      <div class="p-2 bd-highlight" style="margin-top: 1.5vh;">
        <%= form.label :accommodates %><br>
        <%= form.text_field :guest_number %>
      </div>

      <div class="p-2 bd-highlight" style="margin-top: 1.5vh;">
        <%= form.label :pricing %><br>
        <%= form.text_field :pricing %>
      </div>

      <div class="p-2 bd-highlight" style="margin-top: 1.5vh;">
        <%= form.label :images %><br>
        <%= form.file_field :images, multiple: true %>
      </div>

      <div class="p-2 bd-highlight" style="margin-top: 1.5vh;">
        <%= form.submit class: "btn btn-outline-dark" %>
      </div>
      
    <% end %>

  </div>

</div>

app/views/listings/show.erb
<div class="container" style="margin-bottom: 7vh">

  <div class="row">

    <div class="col-8 mt-1">
      <div style="display: table; width: 90%; margin: 20px auto;">

        <% if !@listing.images.blank? %>
          <% @listing.images.each do |image| %>
            <%= image_tag image.thumb.url style:"display: table-cell; text-align: center; width: 16%;" %>
          <% end %>
        <% else %>
          <img src="https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?ixlib=rb-0.3.5&s=6286e40d53d85d1fe9fb0f2fae05c173&auto=format&fit=crop&w=1050&q=80" style="display: table-cell; text-align: center; width: 45vw;">
          <br/>
        <% end %>
      </div>

      <h1>
        <%= @listing.title %> 
        <% if current_user != nil && current_user.id == @listing.user_id %>
          <a style="margin-left: 1vw;" href="<%= @listing.id %>/edit" class="btn btn-outline-secondary btn-sm" role="button" aria-pressed="true">Edit Listing</a>
        <% end %>
      </h1>

      <h3>in <a href=""><%= @listing.city %></a></h3>

      <div style="margin-top: 2vh;">
        Listing Status: <%= @listing.verification %>
      </div>

      <% if current_user.superadmin? || current_user.moderator? %>
      	<% if !@listing.verification %>
      		<%= link_to 'verify this listing', verify_path(@listing), method: :patch %>
      	<% else %>
      		<%= link_to 'unverify', verify_path(@listing), method: :patch %>
      	<% end %>
      <% end %>

      <h4 style="margin-top: 2vh;">Owner: <a href="/users/<%= @listing.user.id %>"><%= @listing.user.name %></a></h4>

      <h3 style="margin-top: 2vh;">Summary: <%= @listing.summary %></h3>

      <h4 style="margin-top: 2vh;"><%= @listing.guest_number %> guests | <%= @listing.home_type %> | <%= @listing.room_type %></h4>

      <h4 style="margin-top: 2vh;">Description: <%= @listing.description %></h4>

      <h4 style="margin-top: 2vh;">Amenities: </h4>
    	<% @listing.amenity.each do |a| %>
    		<li><%= a %></li>
    	<% end %>
    </div>

    <div class="col-4">
      <h3 class="mt-4">$<%= @listing.pricing %> per night </h3>

      <h3 style="margin-top: 2vh;">Dates</h3>

      <%= form_with scope: :reservation, url: listing_reservations_path(@listing), local: true do |form| %>

        <div style="margin-top: 2vh;">
          <%= form.label :check_in %><br>
          <%= form.text_field :start_date, id: "datepicker1", width: 276 %>
        </p>

        <div>
          <%= form.label :check_out %><br>
          <%= form.text_field :end_date, id: "datepicker2", width: 276  %>
        </div>

        <div style="margin-top: 2.5vh;">
          <%= form.label :special_request %><br>
          <%= form.text_field :special_request %>
        </div>

        <div style="margin-top: 3vh;">
          <% if current_user != nil && current_user.id == @listing.user_id %>
            <button type="button" class="btn btn-outline-dark" disabled>Save Reservation</button>
          <% else %>
            <%= form.submit class: "btn btn-outline-dark" %>
          <% end %>
        </div>

      <% end %>
    </div>

  </div>

</div>

<script>
  $('#datepicker1').datepicker({
  	format: 'dd/mm/yyyy',
      uiLibrary: 'bootstrap4'
  });

  $('#datepicker2').datepicker({
  	format: 'dd/mm/yyyy',
      uiLibrary: 'bootstrap4'
  });
</script>