config/routes.rb
Rails.application.routes.draw do

  get 'homepage/index'
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create]

  # resources generate an id, in this case user's id
  	# to override users,controller for users is changed from "clearance/users" to "users"
  resources :users, controller: "users", only: [:create, :edit, :update, :show, :index] do
	# get "/users" => "users#index"
	# get "/users/:id" => "users#show"

  	# resource doesn't generate an id (password is just a column, not a table)
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  	# leads to views => welcome => index
	  root 'welcome#index'

  	# page with sign up form             #new is the method used
  	get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  	delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  	get "/sign_up" => "users#new", as: "sign_up"

	# user clicked on form -> google, users will get redirected back
	get "/auth/:provider/callback" => "sessions#create_from_omniauth"

	# homepage
	get "/homepage" => "homepage#index"
  
	# nested routes
	resources :listings do
    resources :reservations
  end
	# replaces:
	# get "/listing" => "listing#index"
	# post "/listing/index" => "listing#create"
	# get "/listing/:id" => "listing#show"
	# get "/listing/:id/edit" => "listing#show#edit"

	patch "/listings/:id/verify" => "listings#verify", as: "verify"

  post "/listings/match" => "listings#match", as: "match"
  post "/listings/search" => "listings#search", as: "search"

  get 'reservations/:id/braintree/new' => 'braintree#new', as: "new_braintree"
  post 'reservations/:id/braintree/checkout' => 'braintree#checkout', as: "checkout_braintree"
  #
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord

	include Clearance::User
	#                          if user is deleted, everything related to the user will be deleted as well
	has_many :authentications, dependent: :destroy
	has_many :listings, dependent: :destroy
	has_many :reservations, dependent: :destroy

	#              0          1           2
	enum role: [:customer, :moderator, :superadmin]

	mount_uploader :image, ImageUploader

	# auth_hash returns requested info in a hash
	def self.create_with_auth_and_hash(authentication, auth_hash)
	   user = self.create!(
	   	# these info are required from a hash from google
	    name: auth_hash["info"]["name"],
	    email: auth_hash["info"]["email"],
	    # password cannot be nil (specified previously)
	    password: SecureRandom.hex(10),
	    gender: auth_hash["info"]["gender"]
	   )

	   # helper method that pushes am authentication object into an existing user
	   user.authentications << authentication
	   return user
	 end

	 # grab google to access google for user data
	 def google_token
	   x = self.authentications.find_by(provider: 'google_oauth2')
	   return x.token unless x.nil?
	 end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController

	def index
		@users = User.all
	end

	# acquire from users => new.html.erb
	def new
		@user = User.new
	end

	def create
		user = User.new(user_params)
		user.save
		redirect_to sign_in_path
	end

	def show
    	@user = User.find(params[:id])
    	# @reservation = Reservation.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])

	end

	def update
		@user = User.find(params[:id])
		@user.update(name: params[:user][:name], gender: params[:user][:gender], image: params[:user][:image])
		flash[:update] = "Profile updated!"
		redirect_to user_path(@user)
	end

	private
	# overriding a certain part of the users controller

# 	def user_from_params
# 	    email = user_params.delete(:email)
# 	    password = user_params.delete(:password)
# 	    name = user_params.delete(:name)
# 	    gender = user_params.delete(:gender)
# 	    age = user_params.delete(:age)

# 	    Clearance.configuration.user_model.new(user_params).tap do |user|
# 	      user.email = email
# 	      user.password = password
# 	      user.name = name
# 	      user.gender = gender
# 	      user.age = age
# 	    end
# 	  end

# 	  def user_params
# 	    params[Clearance.configuration.user_parameter] || Hash.new
# 	  end
# 	end

	def user_params
  	  # params will require a user key, and user key will require the 5 keys
      params.require(:user).permit(:email, :password, :name)
    end


end

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email, class: "font-weight-bold" %>
  <!-- _ means its a partial -->
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password, class: "font-weight-bold" %>
  <%= form.password_field :password %>
</div>

<div class="text-field">
  <%= form.label :name, class: "font-weight-bold" %>
  <%= form.text_field :name, type: 'name' %>
</div>

app/views/users/edit.erb
<div class="container" style="margin-bottom: 7vh">

	<h3>User ID: <%= @user.id %></h3>
	<h3>Name: <%= @user.name %></h3>

	<hr/>

	<h4>Available edit fields:</h4>

	<%= form_with scope: @user, url: user_path, method: "patch", local: true do |form| %>

		<div class="text-field">
			<%= form.label :name %><br />
			<%= form.text_field :name, type: 'name' %>
		</div>


		<div>
			<%= form.label :gender %><br />
			<%= form.radio_button :gender, "male" %> Male
			<%= form.radio_button :gender, "female" %> Female
			<%= form.radio_button :gender, "other" %> Other
		</div>

		<div>
			<%= form.file_field :image %>
		</div>

		<div class="submit-field">
			<%= form.submit %>
			<!-- or -->
			<!-- form.submit "some words that you wish to change to" -->
		</div>

	<% end %>

</div>

app/views/users/index.erb
<% i = 1 %>
<% @users.order("id").each do |user| %>
	<h4>
		<%= i.to_s %>. 
		<a href="/users/<%= user.id %>"><%= user.name %></a>
	</h4>
	<% i += 1 %>
<% end %>

app/views/users/new.html.erb
<!-- sign up page -->

<!DOCTYPE html>
<html>
<head>

  <title></title>

  <style>
    body {
      background-image: url("http://natbg.com/wp-content/uploads/2017/01/mountains-cold-landscape-winter-maountain-mountain-view-desktop-backgrounds.jpg");
    }
  </style>

</head>

<body>
  <div class="d-flex flex-column bd-highlight mb-3 text-center" style="display: block; margin-top: 20vh; margin-left: auto; margin-right: auto; width: auto;">

<div id="clearance" class="sign-up">
  <div class="p-2 bd-highlight">
    <h2 style="color: #fff"><%= t(".title") %></h2>
  </div>

  <div class="p-2 bd-highlight" style="color: #fff">
    <%= form_for @user do |form| %>
    <!-- _ means its a partial -->
    <!-- so this file connects with _form.html.erb -->
    <%= render partial: '/users/form', object: form %>
  </div>

    <div class="p-2 bd-highlight submit-field">
      <%= form.submit style: "background-color: #000; color: #fff; border: none;"%>
      <!-- or -->
      <!-- form.submit "some words that you wish to change to" -->
    </div>

  <% end %>
</div>

  </div>
</body>
</html>

app/views/users/show.erb
<div class="container" style="margin-bottom: 7vh">

	<% if signed_in? %>
		<% case current_user.role %>
		<% when 'customer' %>
			<%= image_tag @user.image.thumb.url.to_s %>
			<h3 class="text-capitalize">
				Name: <%= @user.name %>
				<% if @user.id == current_user.id %>
					<a href="/users/<%= @user.id %>/edit" class="btn btn-outline-secondary btn-sm ml-1" role="button" aria-pressed="true">Edit Profile</a>
				<% end %>
			</h3>
			<hr/>
			<h3>
				Listings of <span class="text-capitalize"><%= @user.name %></span>
				<% if @user.id == current_user.id %>
					<a href="/listings/new" class="btn btn-outline-primary btn-sm ml-1" role="button" aria-pressed="true">Add Listing</a>
				<% end %>
			</h3>
			
			<div class="row">
				<% @user.listings.order("created_at DESC").each do |listing| %>
					<!-- 					this id is for the card that's to be faded out when deleted (destroy.js.erb) -->
					<div class="col-4" id="<%= listing.id %>">
						<div class="card mb-4">
							<% if listing.images != [] %>
								<%= image_tag listing.images[0].thumb.url %><br />
							<% else %>
								<img class="card-img-top" src="https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?ixlib=rb-0.3.5&s=6286e40d53d85d1fe9fb0f2fae05c173&auto=format&fit=crop&w=1050&q=80" alt="Card image cap">
							<% end %>
							<div class="card-body">
								<a href="/listings/<%= listing.id %>" class="card-title"><%= listing.title %></h5></a>
								<% if current_user != nil && current_user.id == listing.user_id %>
									<a href="/listings/<%= listing.id %>/edit" class="btn btn-outline-secondary btn-sm ml-1" role="button" aria-pressed="true">Edit</a>
									<!--                                                             accepts a json action -->
									<%= link_to "Delete", listing_path(listing.id), method: :DELETE, remote:true, class: "btn btn-outline-danger btn-sm ml-1", data: { confirm: 'Are you sure that you want to delete this listing?'} %>
								<% else %>
									<a href="/listings/<%= listing.id %>" class="btn btn-outline-secondary btn-sm ml-1" role="button" aria-pressed="true">Book now</a>
								<% end %>

								<p class="card-text"><%= listing.room_type %> • <%= listing.city %></p>
							</div>
						</div>
					</div>
				<% end %>
			</div>

			<% if @user.id == current_user.id %>
				<hr/>
				<h3>Your Reservations</h3>
				<% i = 1 %>
				<% @user.reservations.each do |reservation| %>
					<h5>
						<%= i.to_s %>. <a href="/listings/<%= reservation.listing.id %>/reservations/<%= reservation.id %>"><%= reservation.listing.city %>, from <%= reservation.start_date %> to <%= reservation.end_date %></a>
					</h5>
					<% i += 1 %>
				<% end %>
			<% end %>

		<% when 'moderator' %>
			<h3>User ID: <%= @user.id %></h3>
			<%= image_tag @user.image.thumb.url.to_s %>
			<h3>Name: <%= @user.name %></h3>
			<h3>Status: <%= @user.role %></h3>
			<hr/>
			<h3>Listings of <%= @user.name %></h3>
			<% i = 1 %>
			<% @user.listings.order("created_at DESC").each do |listing| %>
				<h5>
					<%= i.to_s %>. 
					<a href="/listings/<%= listing.id %>"><%= listing.title %></a>
					<a href="/listings/<%= listing.id %>" class="btn btn-outline-secondary btn-sm ml-1" role="button" aria-pressed="true">Book now</a>
				</h5>
				<% i += 1 %>
			<% end %>
		<% when 'superadmin' %>
			<h3>User ID: <%= @user.id %></h3>
			<%= image_tag @user.image.thumb.url.to_s %>
			<h3>Name: <%= @user.name %></h3>
			<h3>Status: <%= @user.role %></h3>
			<h4><%= @user.inspect %></h4>
			<a href="/users/<%= @user.id %>/edit" class="btn btn-outline-secondary mt-1" role="button" aria-pressed="true">Edit Profile</a>
			<hr/>
			<h3>Listings of <%= @user.name %>
			<a href="/listings/new" class="btn btn-outline-primary btn-sm ml-1" role="button" aria-pressed="true">Add Listing</a>
			</h3> 
			<% i = 1 %>
			<% @user.listings.order("created_at DESC").each do |listing| %>
				<h5>
					<%= i.to_s %>. 
					<a href="/listings/<%= listing.id %>"><%= listing.title %></a>
					<a href="/listings/<%= listing.id %>" class="btn btn-outline-secondary btn-sm ml-1" role="button" aria-pressed="true">Book now</a>
					<a href="/listings/<%= listing.id %>/edit" class="btn btn-outline-secondary btn-sm ml-1" role="button" aria-pressed="true">Edit</a>
					<!--                                                             accepts a json action -->
					<%= link_to "Delete", listing_path(listing.id), method: :DELETE, remote:true, class: "btn btn-outline-danger btn-sm ml-1", data: { confirm: 'Are you sure that you want to delete this listing?'} %>
				</h5>
				<% i += 1 %>
			<% end %>
			<hr/>
			<h3>Reservations of <span class="text-capitalize"><%= @user.name %></h3></span>
			<% i = 1 %>
			<% @user.reservations.each do |reservation| %>
				<h5>
					<%= i.to_s %>. <a href="/listings/<%= reservation.listing.id %>/reservations/<%= reservation.id %>"><%= reservation.listing.city %>, from <%= reservation.start_date %> to <%= reservation.end_date %></a>
				</h5>
				<% i += 1 %>
			<% end %>
		<% end %>
	<% else %>
		<h3>Name: <%= @user.name %></h3>
	<% end %>

</div>