config/routes.rb
Rails.application.routes.draw do

  get 'homepage/index'
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create]

  # resources generate an id, in this case user's id
  	# to override users,controller for users is changed from "clearance/users" to "users"
  resources :users, controller: "users", only: [:create, :edit, :update, :show, :index] do
	# get "/users" => "users#index"
	# get "/users/:id" => "users#show"

  	# resource doesn't generate an id (password is just a column, not a table)
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  	# leads to views => welcome => index
	  root 'welcome#index'

  	# page with sign up form             #new is the method used
  	get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  	delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  	get "/sign_up" => "users#new", as: "sign_up"

	# user clicked on form -> google, users will get redirected back
	get "/auth/:provider/callback" => "sessions#create_from_omniauth"

	# homepage
	get "/homepage" => "homepage#index"
  
	# nested routes
	resources :listings do
    resources :reservations
  end
	# replaces:
	# get "/listing" => "listing#index"
	# post "/listing/index" => "listing#create"
	# get "/listing/:id" => "listing#show"
	# get "/listing/:id/edit" => "listing#show#edit"

	patch "/listings/:id/verify" => "listings#verify", as: "verify"

  post "/listings/match" => "listings#match", as: "match"
  post "/listings/search" => "listings#search", as: "search"

  get 'reservations/:id/braintree/new' => 'braintree#new', as: "new_braintree"
  post 'reservations/:id/braintree/checkout' => 'braintree#checkout', as: "checkout_braintree"
  #
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  
  <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
  
  <link href="https://cdn.jsdelivr.net/npm/gijgo@1.9.6/css/gijgo.min.css" rel="stylesheet" type="text/css" />
  
  <script src="https://cdn.jsdelivr.net/npm/gijgo@1.9.6/js/gijgo.min.js" type="text/javascript"></script>
  
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>

  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tag %>

</head>
<body>

<!-- Navbar top -->

      <% if signed_in? %>
        <nav class="navbar sticky-top navbar-expand-lg navbar-light" style="background-color: #fff; padding:1.5%">
        <div class="container">
          <!-- logo -->
          <a class="airbnb" href="/homepage">
            <img src="https://cdn2.iconfinder.com/data/icons/rental-icon/240/airbnb-512.png" style="width:31.5px; height:31.5px; margin-right:0.5vw;" alt="">
          </a>

          <!-- search bar -->
          <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle mr-1" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              What are you looking for?
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">

            <%= form_with url: search_path, local: true, html: { class: 'form-inline my-2 my-lg-0' } do |f| %>
              <input name="city_search" class="form-control mr-sm-2 dropdown-item" type="search" placeholder="City, eg. Selangor" aria-label="Search" style="width:45vw;" id="city_search" list="city_list">
              <datalist id="city_list"></datalist>

              <input name="title_search" class="form-control mr-sm-2 dropdown-item" type="search" placeholder="Title" aria-label="Search" style="width:45vw;" id="title_search" list="title_list">
              <datalist id="title_list"></datalist>
          </div>
        </div>

          <button class="btn btn-sm btn-outline-secondary" type="submit">Search</button>

        <% end %>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <!-- Put something here if needed -->
          </ul>
          <ul class="nav navbar-nav navbar-right">
  <!--           <li class="nav-item">
              <p class="nav-link mb-0">Signed in as: <%= current_user.email %></p>
            </li> -->
            <li class="nav-item">
              <%= link_to 'Profile', user_path(current_user), class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Log Out', sign_out_path, method: :delete, class: "nav-link" %>
            </li>

          <% else %>
            <nav class="navbar sticky-top navbar-expand-lg navbar-dark" style="background-color: #66000; padding:1.5%">
            <div class="container">
            <!-- <a class="navbar-brand" href="#">Airbnb</a> -->
              <!-- logo -->
            <a class="airbnb" href="/">
              <img src="https://assets-cdn.github.com/images/modules/logos_page/Octocat.png" style="width:39px; height:35px; margin-right:1vw;" alt="">
            </a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <!-- Put something here if needed -->
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if request.path_info == '/sign_up' %>
              <li class="nav-item active">
                <%= link_to 'Log In', sign_in_path, class: 'nav-link' %>
              </li>
              <li class="nav-item active">
                <%= link_to 'Log in with Google', "/auth/google_oauth2", class: 'nav-link' %>
              </li>
            <% elsif request.path_info == '/sign_in' %>
              <li class="nav-item active">
                <%= link_to 'Sign Up', sign_up_path, class: 'nav-link' %>
              </li>
              <li class="nav-item active">
                <%= link_to 'Log in with Google', "/auth/google_oauth2", :class => 'nav-link' %>
              </li>
            <% else %>
              <li class="nav-item active">
                <%= link_to 'Sign Up', sign_up_path, class: 'nav-link' %>
              </li>
              <li class="nav-item active">
                <%= link_to 'Log In', sign_in_path, class: 'nav-link' %>
              </li>
              <li class="nav-item active">
                <%= link_to 'Log in with Google', "/auth/google_oauth2", class: 'nav-link' %>
              </li>
            <% end %>
          <% end %>
          </ul>
        </div>
    </div>
  </nav>
  <!-- /Navbar top -->

  <!-- flash will show on top of each page, unless this is removed (then self specification is required) -->
  <div id="flash">
    <% flash.each do |key, value| -%>
      <div class="alert alert-info" id="flash_<%= key %>"><%=h value %></div>
    <% end %>
  </div>

    <!-- Navbar bottom -->
  <nav class="navbar fixed-bottom navbar-light" style="background-color: #66000">
    <div class="container">

    <span class="navbar-text">
    </span>

      <div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent2" aria-controls="navbarSupportedContent2" aria-expanded="false" aria-label="Toggle navigation" style="border: none; background-color: #fff; padding-bottom: 5px;">
          <span class="font-weight-normal" style="color: #666; font-size: 15px;">Terms, Privacy & More</span>
        </button>
      </div>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent2" style="background-color: #fff">
        <ul class="navbar-nav mr-auto">
          <!-- Put something here if needed -->
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <!-- Airbnb -->
          <div class="navbar-brand">
            Airbnb
          </div>

          <li class="nav-item">
            <a class="nav-link" href="#">Terms</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="#">Privacy</a>
          </li>

          <li class="nav-item" >
            <a class="nav-link" href="#">Site Map</a>
          </li>
 
        </ul>

        <div class='alert alert-error'>
          <button type="button" class="close" aria-label="Close" data-toggle="collapse" data-target="#navbarSupportedContent2">
          <span aria-hidden="true">&times;</span>
          </button>
        </div>
      </div>
    </div>
  </nav>
  <!-- /Navbar bottom -->

  <%= yield %>
  
</body>
</html>